name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: metrics
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: github-metrics.svg

          plugin_topics: yes
          plugin_topics_sort: activity
          plugin_topics_limit: 20
          plugin_topics_mode: icons

          plugin_habits: yes
          plugin_habits_facts: no
          plugin_habits_charts: yes

          plugin_wakatime: yes
          plugin_wakatime_languages_other: true
          plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, os
          plugin_wakatime_days: 365
          plugin_wakatime_limit: 5
          plugin_wakatime_repositories_visibility: private
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}

  github-stack:
    runs-on: ubuntu-latest
    environment: 
      name: metrics
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          base: ""
          token: ${{ secrets.METRICS_TOKEN }}
          filename: github-stacks.svg

          plugin_leetcode: yes
          plugin_leetcode_sections: solved, skills, recent

          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
