name: Metrics
on:
  schedule: [{cron: "0 * * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: metrics
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: github-metrics.svg

          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: no
          plugin_habits_days: 30
          plugin_habits_charts_type: classic

          plugin_languages: yes
          plugin_languages_indepth: yes

          plugin_wakatime: yes
          plugin_wakatime_languages_other: true
          plugin_wakatime_sections: time, time-graphs projects, projects-graphs, languages, languages-graphs, editors, editors-graphs, os, os-graphs
          plugin_wakatime_days: 7
          plugin_wakatime_limit: 50
          plugin_wakatime_repositories_visibility: all
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}

          plugin_stars: yes
          plugin_stars_limit: 3

          plugin_leetcode: yes
          plugin_leetcode_sections: solved, skills, recent
          
