name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 * * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: metrics
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: github-metrics.svg

          plugin_wakatime: yes
          plugin_wakatime_languages_other: true
          plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, os
          plugin_wakatime_days: 365
          plugin_wakatime_limit: 5
          plugin_wakatime_repositories_visibility: all
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}

  github-stack:
    runs-on: ubuntu-latest
    environment: 
      name: metrics
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          base: ""
          token: ${{ secrets.METRICS_TOKEN }}
          filename: github-stacks.svg

          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          plugin_habits: yes
          plugin_habits_facts: no
          plugin_habits_charts: yes
          plugin_habits_charts_type: classic

          plugin_languages: yes
          plugin_languages_sections: recently-used
          plugin_languages_recent_load: 400
          plugin_languages_recent_days: 14

          plugin_wakatime: yes
          plugin_wakatime_languages_other: true
          plugin_wakatime_sections: time, time-graphs projects, projects-graphs, languages, languages-graphs, editors, editors-graphs, os, os-graphs
          plugin_wakatime_days: 7
          plugin_wakatime_limit: 50
          plugin_wakatime_repositories_visibility: all
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}

          plugin_starlists: yes
          plugin_starlists_languages: yes
          plugin_starlists_limit_languages: 10
          plugin_starlists_limit_repositories: 5

          plugin_leetcode: yes
          plugin_leetcode_sections: solved, skills, recent
